apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k3os-6802
spec:
  rules:
  - host: k3os-6802
    http:
      paths:
        - path: /grafana
          pathType: Prefix
          backend:
            service:
              name: grafana
              port: 
                name: http-grafana
        - path: /
          pathType: Prefix
          backend:
            service:
              name: graphite
              port: 
                name: graphite-ui
        - path: /prometheus
          pathType: Prefix
          backend:
            service:
              name: prometheus
              port: 
                name: http-prometheus
