apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
spec:
  rules:
  - host: columbo
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana
              port: 
                name: http-grafana
